source 'http://rubygems.org'

gem 'rails', '3.1.11'
gem 'sqlite3-ruby', :require => 'sqlite3'

gem "devise_ldap_authenticatable", :path => "../../"
gem 'devise-encryptable'

group :test do
  gem 'mocha'
  gem 'shoulda'
  gem 'factory_girl_rails', '~> 1'
  gem 'factory_girl', '~> 1'
  gem "cucumber-rails"
  gem "database_cleaner"
  gem "capybara"
  gem "launchy"
  gem "autotest-rails"
  gem "ZenTest"
  gem "autotest-growl"
  gem 'turn'
end

group :debug do
  gem (RUBY_VERSION =~ /^1\.9/ ? "debugger" : "ruby-debug")
end